pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'main', credentialsId: 'gitlab_credential_id', url: 'http://172.31.30.98/my_projects/weather'
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose up -d --build'     
            }
        }
        stage('Push to Docker Hub') {
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'HUB_USER', passwordVariable: 'HUB_TOKEN')]) {                      
                    sh '''
                        docker login -u $HUB_USER -p $HUB_TOKEN 
                        docker image tag weather_k8s $HUB_USER/weather_k8s:$BUILD_NUMBER
                        docker image push $HUB_USER/weather_k8s:$BUILD_NUMBER
                        docker image tag weather_k8s $HUB_USER/weather_k8s:latest
                        docker image push $HUB_USER/weather_k8s:latest
                    '''
                }
            }           
        }
    }
    post {
        success {
            echo 'Triggering deployment pipeline'
            build job: "weather_deploy", parameters: [string(name: 'BUILD_NUM', value: "$BUILD_NUMBER"), string(name: 'REP', value: "$REPLICA")] ,wait: true
        }
    }
}
